### ISSUE TITLE
Linux Hardcore Ender Mod music disk bug.

### ISSUE THREAD

**Issue by TheBlueTroll** [TPPIDev/TestPackPleaseIgnore#537]
The Bug is that any music disk from Hardcore ender mod does not play on linux, and during loading this error is shown: 
"2014-10-28 16:39:03 [INFO] [STDERR] java.io.FileNotFoundException: home/Hack/ftbinstall/ramdisk/TPPI/minecraft/mods/HardcoreEnderExpansion.zip (No such file or directory)
2014-10-28 16:39:03 [INFO] [STDERR] 	at java.util.zip.ZipFile.open(Native Method)
2014-10-28 16:39:03 [INFO] [STDERR] 	at java.util.zip.ZipFile.<init>(Unknown Source)
2014-10-28 16:39:03 [INFO] [STDERR] 	at java.util.zip.ZipFile.<init>(Unknown Source)
2014-10-28 16:39:03 [INFO] [STDERR] 	at java.util.zip.ZipFile.<init>(Unknown Source)
2014-10-28 16:39:03 [INFO] [STDERR] 	at chylex.hee.system.sound.MusicAndSoundManager.loadMusicFromZip(MusicAndSoundManager.java:121)
2014-10-28 16:39:03 [INFO] [STDERR] 	at chylex.hee.system.sound.MusicAndSoundManager.onSoundLoad(MusicAndSoundManager.java:56)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraftforge.event.ASMEventHandler_177_MusicAndSoundManager_onSoundLoad_SoundLoadEvent.invoke(.dynamic)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraftforge.event.EventBus.post(EventBus.java:108)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.client.audio.SoundManager.func_110549_a(SoundManager.java:102)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:99)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:87)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:543)
2014-10-28 16:39:03 [INFO] [STDERR] 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:265)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.client.main.Main.main(SourceFile:101)
2014-10-28 16:39:03 [INFO] [STDERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-10-28 16:39:03 [INFO] [STDERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-10-28 16:39:03 [INFO] [STDERR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-10-28 16:39:03 [INFO] [STDERR] 	at java.lang.reflect.Method.invoke(Unknown Source)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2014-10-28 16:39:03 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2014-10-28 16:39:03 [SEVERE] [ForgeModLoader] [HardcoreEnderExpansion] Error loading music - Error declaring ZipFile
2014-10-28 16:39:03 [INFO] [ForgeModLoader] [HardcoreEnderExpansion] Loaded 0 music tracks from folder"

Now Obviously the error is "java.io.FileNotFoundException: home/Hack/ftbinstall/ramdisk/TPPI/minecraft/mods/HardcoreEnderExpansion.zip (No such file or directory)", but the bug is that it is does infact Exist, but it is missing a / at the beginning i.e
home/Hack/ftbinstall/ramdisk/TPPI/minecraft/mods/HardcoreEnderExpansion.zip becomes
/home/Hack/ftbinstall/ramdisk/TPPI/minecraft/mods/HardcoreEnderExpansion.zip

the shortlist of how to fix is to add a os check, and if linux/unix/ other *nix os, prefix the / to the path.

Minecraft 1.6.4 from modpack TPPI (Test Pack Please Ignore) v 1.2.2 using HEE mod version 1.5
Running on Lubuntu 14.10 (latest Lubuntu Distribution) on oracle java 1.8.0u5 Linux Edition

Now on the right github, sorry to chylex for unnessary annoyance.

**Comment by chylex** [comment]
Close please, outdated => won't fix.
