### ISSUE TITLE
Server startup isn't working

### ISSUE THREAD

**Issue by Project-5401** [TPPIDev/TestPackPleaseIgnore#635]
I'm trying to start a server to play with my friend, and as far as I know, to do that, you have to run the bat file before actually starting up the server. The problem is, when I launch the bat, it says this:

C:\Users\XXXXX\Desktop\Minecraft\Servers\TPPI>java -Xmx3200M -Xms1024M -XX:+UseCo
ncMarkSweepGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:PermSi
ze=128m -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -jar minecraft_server.jar no
gui
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; suppor
t was removed in 8.0
Feb 20, 2015 4:02:07 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
Feb 20, 2015 4:02:08 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweak
er
Feb 20, 2015 4:02:08 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
2015-02-20 16:02:08 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965
for Minecraft 1.6.4 loading
2015-02-20 16:02:08 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Serv
er VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program
 Files\Java\jre1.8.0_25
2015-02-20 16:02:08 [WARNING] [ForgeModLoader] The coremod codechicken.core.laun
ch.DepLoader does not have a MCVersion annotation, it may cause issues with this
 version of Minecraft
2015-02-20 16:02:08 [WARNING] [ForgeModLoader] The coremod worldcore.asm.WCFMLLo
adingPlugin does not have a MCVersion annotation, it may cause issues with this
version of Minecraft
2015-02-20 16:02:08 [WARNING] [ForgeModLoader] The coremod am2.preloader.AM2Prel
oaderContainer does not have a MCVersion annotation, it may cause issues with th
is version of Minecraft
2015-02-20 16:02:08 [INFO] [ForgeModLoader] AMCore initializing...stand back!  I
'm going to try MAGIC!
2015-02-20 16:02:08 [WARNING] [ForgeModLoader] The coremod appeng.transformer.Ap
pEngCore does not have a MCVersion annotation, it may cause issues with this ver
sion of Minecraft
2015-02-20 16:02:08 [INFO] [ForgeModLoader] [AppEng] Core Init
2015-02-20 16:02:08 [WARNING] [ForgeModLoader] The coremod biomesoplenty.asm.BOP
FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with
this version of Minecraft
2015-02-20 16:02:11 [INFO] [STDERR] Warning: version of ForgeMultipart-universal
-1.6.4-, 1.0.0.250 is newer than request 1.0.0.244
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod codechicken.core.laun
ch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issu
es with this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugi
n does not have a MCVersion annotation, it may cause issues with this version of
 Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod denoflionsx.denLib.Co
reMod.denLibCore does not have a MCVersion annotation, it may cause issues with
this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod mcp.mobius.evoc.asm.C
oreDescription does not have a MCVersion annotation, it may cause issues with th
is version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod mods.immibis.microblo
cks.coremod.MicroblocksCoreMod does not have a MCVersion annotation, it may caus
e issues with this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod ic2.core.coremod.IC2c
ore does not have a MCVersion annotation, it may cause issues with this version
of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod invtweaks.forge.asm.F
MLPlugin does not have a MCVersion annotation, it may cause issues with this ver
sion of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod logisticspipes.asm.Lo
gisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues
 with this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod mekanism.common.asm.L
oadingHook does not have a MCVersion annotation, it may cause issues with this v
ersion of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod mcp.mobius.mobiuscore
.asm.CoreDescription does not have a MCVersion annotation, it may cause issues w
ith this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.N
EICorePlugin does not have a MCVersion annotation, it may cause issues with this
 version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod openblocks.OpenBlocks
CorePlugin does not have a MCVersion annotation, it may cause issues with this v
ersion of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod openeye.CorePlugin do
es not have a MCVersion annotation, it may cause issues with this version of Min
ecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod openmods.OpenModsCore
Plugin does not have a MCVersion annotation, it may cause issues with this versi
on of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod denoflionsx.Pluginsfo
rForestry.Core.CoreMod.PfFCoreMod does not have a MCVersion annotation, it may c
ause issues with this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod codechicken.core.laun
ch.DepLoader does not have a MCVersion annotation, it may cause issues with this
 version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod mrtjp.projectred.comp
atibility.CompatibilityCorePlugin does not have a MCVersion annotation, it may c
ause issues with this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod resonant.core.Resonan
tPluginLoader does not have a MCVersion annotation, it may cause issues with thi
s version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod net.minecraftforge.le
x.sortfix.CorePlugin does not have a MCVersion annotation, it may cause issues w
ith this version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod tconstruct.preloader.
TConstructLoaderContainer does not have a MCVersion annotation, it may cause iss
ues with this version of Minecraft
2015-02-20 16:02:11 [INFO] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR!
 *zap*
2015-02-20 16:02:11 [INFO] [TCon-Preloader] Constructing preloader (Modules: [tc
onstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])

2015-02-20 16:02:11 [INFO] [TCon-Preloader] Found a properties file. Attempting
load...
2015-02-20 16:02:11 [INFO] [TCon-Preloader] Loaded properties successfully. Usin
g specified settings.
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod universalelectricity.
core.UELoader does not have a MCVersion annotation, it may cause issues with thi
s version of Minecraft
2015-02-20 16:02:11 [WARNING] [ForgeModLoader] The coremod codechicken.core.laun
ch.DepLoader does not have a MCVersion annotation, it may cause issues with this
 version of Minecraft
2015-02-20 16:02:11 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fm
l.common.launcher.FMLInjectionAndSortingTweaker
2015-02-20 16:02:11 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fm
l.common.launcher.FMLDeobfTweaker
2015-02-20 16:02:11 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.com
mon.launcher.FMLInjectionAndSortingTweaker
2015-02-20 16:02:11 [SEVERE] [ForgeModLoader] Unable to launch
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.remove(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:48)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:17)

C:\Users\XXXXX\Desktop\Minecraft\Servers\TPPI>pause
Press any key to continue . . .

And stops at that. All the videos and stuff I found say to do just that, and they don't encounter this problem. What's up?

**Comment by TehNut** [comment]
http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

Put in mods folder.
