### ISSUE TITLE
Lots of NPEs and eventual crash (TPPI2)

### ISSUE THREAD

**Issue by DoctahFrank** [TPPIDev/TestPackPleaseIgnore#644]
I downloaded the pack normally through the FTB Launcher and it ran fine, but once I got to the main menu, I noticed that the minimap mod was throwing tons of NullPointerExceptions like so:

[20:09:16] [Thread-27/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[20:09:16] [Thread-27/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.minimap.minimap.Minimap.getCaving(Minimap.java:496)
[20:09:16] [Thread-27/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.minimap.minimap.Minimap.access$100(Minimap.java:26)
[20:09:16] [Thread-27/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.minimap.minimap.Minimap$MapLoader.run(Minimap.java:105)
[20:09:16] [Thread-27/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.run(Unknown Source)

This leads the game to eventually craft and I have to use the task manager to end the FTB Launcher and Console. Can anyone help me with this?

**Comment by DoctahFrank** [comment]
It fixed itself I guess.
